import type { GetStaticProps, NextPage } from "next";

import Head from "next/head";
import api from "@services/api";
import Navbar from "@components/organisms/Navbar";

type HomeProps = {
  movies: Movie[];
};

const Home: NextPage<HomeProps> = ({ movies }) => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  console.log("\x1b[32m", "\n✅ Index Page created with success");

  const {
    data: { results: movies },
  }: { data: { results: Movie[] } } = await api.get(`movie/popular`);

  return {
    props: {
      movies,
    },
  };
};

export default Home;
